package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_1.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'TeamcityEnvironment01_HttpsGithubComCharishmakTeamcityGitRefsHeadsMaste'
in the project with id = 'TeamcityEnvironment01', and delete the patch script.
*/
create(RelativeId("TeamcityEnvironment01"), GitVcsRoot({
    id("TeamcityEnvironment01_HttpsGithubComCharishmakTeamcityGitRefsHeadsMaste")
    name = "https://github.com/charishmak/teamcity.git#refs/heads/master"
    url = "https://github.com/charishmak/teamcity.git"
    authMethod = password {
        userName = "charishmak"
        password = "credentialsJSON:711d53f8-5f3b-4f50-8fa3-822f1488d750"
    }
}))

